### ISSUE TITLE
I'm Not Enjoying This

### ISSUE THREAD

**Issue by r14c** [minisats/minisats#2]
I would like to help this project go somewhere but I don't know where we're going, I don't feel like there is any real communication (despite what looks like efforts to establish communication channels).

Y'all can keep what I've done already, unfortunately I can't say its finished by any means but I really don't care. Nobody is really contributing in any case.

I'm out.

**Comment by minisat-maker** [comment]
Sorry about this. I haven't been able to find as much time to put into this as I thought I would be able to. It also probably doesn't help that out of the three people who seem to be interested in working on this, you're the only one who seems comfortable with github.
